# Generated by Django 3.2.16 on 2023-03-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/products/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='measure',
            field=models.CharField(blank=True, choices=[('piece', 'piece'), ('kg', 'kg'), ('l', 'l'), ('500 g', '500 g'), ('100 g', '100 g'), ('50 g', '50 g'), ('500 ml', '500 ml'), ('100 ml', '100 ml'), ('50 ml', '50 ml')], max_length=20, null=True),
        ),
    ]
